-- Seed data (reference data only: no fake measurements, workouts or achievement histories).
insert into members (id, slug, name, display_name, avatar_url) values
  ('00000000-0000-4000-8000-000000000001','amr','AMR','AMR','/avatars/amr.png'),
  ('00000000-0000-4000-8000-000000000002','aman','AMAN','AMAN','/avatars/aman.png'),
  ('00000000-0000-4000-8000-000000000003','shady','SHADY','SHADY','/avatars/shady.png')
on conflict (slug) do nothing;
insert into member_goals (member_id) select id from members on conflict do nothing;
insert into app_settings (key, value) values ('timezone', '"Africa/Cairo"'::jsonb) on conflict (key) do nothing;
insert into exercise_categories (slug, name, sort_order) values
  ('upper-body','Upper Body',0),
  ('lower-body','Lower Body',1),
  ('push','Push',2),
  ('pull','Pull',3),
  ('legs','Legs',4),
  ('core','Core',5),
  ('cardio','Cardio',6),
  ('free-weights','Free Weights',7)
on conflict (slug) do nothing;
insert into exercises (slug, name, kind, equipment, primary_muscles, secondary_muscles, instructions, safety_notes, youtube_query) values
  ('leg-press','Leg Press','resistance','Leg press machine',array['Quadriceps','Glutes']::text[],array['Hamstrings','Calves']::text[],'Sit with your back and hips flat on the pad and place your feet shoulder-width on the platform. Lower the platform under control until your knees are bent about 90 degrees, then press through your whole foot without locking the knees.','Keep your lower back and hips on the pad, never bounce at the bottom, and do not lock out your knees at the top.','Leg Press proper form tutorial'),
  ('barbell-squat','Barbell Back Squat','resistance','Barbell and rack',array['Quadriceps','Glutes']::text[],array['Hamstrings','Core','Lower back']::text[],'Set the bar across your upper back, brace your core, and sit down and back while keeping your chest up and knees tracking over your toes. Drive up through the middle of your feet.','Use safety bars in the rack, keep a neutral spine, and choose a weight that lets you keep control of every rep.','Barbell Back Squat proper form tutorial'),
  ('goblet-squat','Goblet Squat','resistance','Dumbbell or kettlebell',array['Quadriceps','Glutes']::text[],array['Core']::text[],'Hold one weight close to your chest, sit between your hips with your chest tall, then stand back up.','Keep your heels down and your spine neutral. Start light to learn the pattern.','Goblet Squat proper form tutorial'),
  ('leg-extension','Leg Extension','resistance','Leg extension machine',array['Quadriceps']::text[],'{}'::text[],'Adjust the pad to sit just above your ankles and the back pad so your knees line up with the machine pivot. Extend your legs smoothly, pause briefly, then lower slowly.','Avoid swinging or using momentum, and use a moderate weight if you have knee discomfort.','Leg Extension proper form tutorial'),
  ('hamstring-curl','Seated Hamstring Curl','resistance','Leg curl machine',array['Hamstrings']::text[],array['Calves']::text[],'Set the pad just above your heels and the thigh pad snug. Curl your heels toward you, squeeze, and return with control.','Do not lift your hips or jerk the weight. Control the lowering phase.','Seated Hamstring Curl proper form tutorial'),
  ('standing-calf-raise','Standing Calf Raise','resistance','Calf raise machine or step',array['Calves']::text[],'{}'::text[],'Rise onto the balls of your feet as high as you can, pause at the top, then lower until you feel a stretch.','Move slowly and use a full range of motion rather than a heavy bounce.','Standing Calf Raise proper form tutorial'),
  ('romanian-deadlift','Romanian Deadlift','resistance','Barbell or dumbbells',array['Hamstrings','Glutes']::text[],array['Lower back','Core']::text[],'With a soft knee bend, push your hips back while the weight slides down your legs and your back stays flat. Stand by driving your hips forward.','Keep the weight close to your body and stop the descent when your back would start to round.','Romanian Deadlift proper form tutorial'),
  ('walking-lunge','Walking Lunge','resistance','Bodyweight or dumbbells',array['Quadriceps','Glutes']::text[],array['Hamstrings','Core']::text[],'Step forward into a long stride, lower your back knee toward the floor, then push through the front foot into the next step.','Keep your torso upright and your front knee stable over your foot.','Walking Lunge proper form tutorial'),
  ('hip-thrust','Hip Thrust','resistance','Bench and barbell or machine',array['Glutes']::text[],array['Hamstrings']::text[],'Rest your upper back on a bench with the weight over your hips. Drive through your heels until your torso is level with the floor, squeeze, and lower under control.','Tuck your chin slightly, avoid over-arching your lower back, and pad the bar.','Hip Thrust proper form tutorial'),
  ('chest-press-machine','Chest Press (Machine)','resistance','Chest press machine',array['Chest']::text[],array['Triceps','Shoulders']::text[],'Set the seat so the handles line up with the middle of your chest. Press forward without locking out, then return slowly until you feel a light chest stretch.','Keep your shoulder blades back against the pad and do not let your shoulders roll forward.','Chest Press (Machine) proper form tutorial'),
  ('bench-press','Barbell Bench Press','resistance','Barbell and bench',array['Chest']::text[],array['Triceps','Shoulders']::text[],'Lie with your eyes under the bar, feet planted and shoulder blades pulled together. Lower the bar to your mid-chest, then press it back up over your shoulders.','Use a spotter or safety arms, and never use a thumbless grip.','Barbell Bench Press proper form tutorial'),
  ('incline-dumbbell-press','Incline Dumbbell Press','resistance','Dumbbells and incline bench',array['Upper chest']::text[],array['Shoulders','Triceps']::text[],'Set the bench to a low-to-moderate incline. Press the dumbbells up and slightly together, then lower them to chest level with your elbows at roughly 45 degrees.','Do not flare your elbows out wide, and bring the weights to the starting position carefully.','Incline Dumbbell Press proper form tutorial'),
  ('machine-shoulder-press','Shoulder Press (Machine)','resistance','Shoulder press machine',array['Shoulders']::text[],array['Triceps']::text[],'Adjust the seat so the handles start near shoulder height. Press upward without shrugging, then lower with control.','Keep your ribs down and avoid arching your lower back.','Shoulder Press (Machine) proper form tutorial'),
  ('dumbbell-shoulder-press','Dumbbell Shoulder Press','resistance','Dumbbells',array['Shoulders']::text[],array['Triceps','Core']::text[],'Hold the dumbbells at shoulder height, brace your core, and press overhead until your arms are almost straight, then lower under control.','Do not lean back excessively, and use lighter weights if you cannot keep your torso steady.','Dumbbell Shoulder Press proper form tutorial'),
  ('lateral-raise','Dumbbell Lateral Raise','resistance','Dumbbells',array['Shoulders']::text[],'{}'::text[],'With a slight bend in your elbows, raise the dumbbells out to the sides to about shoulder height and lower slowly.','Use light weights and do not swing your body to lift them.','Dumbbell Lateral Raise proper form tutorial'),
  ('triceps-pushdown','Cable Triceps Pushdown','resistance','Cable machine',array['Triceps']::text[],'{}'::text[],'Keep your elbows pinned at your sides and push the handle down until your arms are straight, then let it rise under control.','Avoid leaning over the weight or letting your elbows drift forward.','Cable Triceps Pushdown proper form tutorial'),
  ('pec-deck-fly','Pec Deck Fly','resistance','Pec deck machine',array['Chest']::text[],array['Shoulders']::text[],'Sit with your back against the pad and bring the handles together in front of your chest with a soft bend in your elbows, then open slowly.','Stop the opening phase when you feel a comfortable stretch, not a strain in your shoulders.','Pec Deck Fly proper form tutorial'),
  ('lat-pulldown','Lat Pulldown','resistance','Cable machine',array['Lats']::text[],array['Biceps','Upper back']::text[],'Grip the bar slightly wider than your shoulders, lean back a little, and pull the bar to your upper chest by driving your elbows down. Let it rise under control.','Do not pull the bar behind your neck and avoid swinging your torso.','Lat Pulldown proper form tutorial'),
  ('seated-cable-row','Seated Cable Row','resistance','Cable machine',array['Upper back','Lats']::text[],array['Biceps']::text[],'Sit tall with a slight knee bend, pull the handle to your lower ribs while squeezing your shoulder blades together, then extend your arms slowly.','Keep your torso steady and do not round your back to reach forward.','Seated Cable Row proper form tutorial'),
  ('pull-up','Pull-Up / Assisted Pull-Up','resistance','Pull-up bar or assisted machine',array['Lats']::text[],array['Biceps','Upper back','Core']::text[],'Start from a full hang, pull your chest toward the bar by driving your elbows down, and lower fully under control. Use assistance if you cannot do full reps yet.','Avoid kipping or swinging. Use the assisted machine to build up gradually.','Pull-Up / Assisted Pull-Up proper form tutorial'),
  ('bent-over-row','Bent-Over Barbell Row','resistance','Barbell',array['Upper back','Lats']::text[],array['Biceps','Lower back']::text[],'Hinge at your hips with a flat back, pull the bar toward your lower ribs, then lower it with control.','Keep your spine neutral, and reduce the weight if your back starts to round.','Bent-Over Barbell Row proper form tutorial'),
  ('dumbbell-biceps-curl','Dumbbell Biceps Curl','resistance','Dumbbells',array['Biceps']::text[],array['Forearms']::text[],'Keep your elbows near your sides, curl the dumbbells up while rotating your palms toward your shoulders, and lower slowly.','Do not swing your torso to lift the weight.','Dumbbell Biceps Curl proper form tutorial'),
  ('hammer-curl','Hammer Curl','resistance','Dumbbells',array['Biceps','Forearms']::text[],'{}'::text[],'Hold the dumbbells with palms facing each other and curl up without rotating your wrists, then lower under control.','Keep your elbows still and your shoulders relaxed.','Hammer Curl proper form tutorial'),
  ('face-pull','Cable Face Pull','resistance','Cable machine with rope',array['Rear shoulders','Upper back']::text[],'{}'::text[],'Set the cable at about face height. Pull the rope toward your face, separating the ends as your elbows go high and wide, then return slowly.','Use a light weight and keep your ribs down.','Cable Face Pull proper form tutorial'),
  ('deadlift','Conventional Deadlift','resistance','Barbell',array['Glutes','Hamstrings','Lower back']::text[],array['Upper back','Core','Forearms']::text[],'Stand with the bar over mid-foot, hinge down with a flat back, brace your core, and stand up by pushing the floor away while keeping the bar close.','Learn the movement with light weights first and never round your lower back under load.','Conventional Deadlift proper form tutorial'),
  ('plank','Plank','resistance','Bodyweight',array['Core']::text[],array['Shoulders','Glutes']::text[],'Support yourself on your forearms and toes with a straight line from head to heels, squeezing your glutes and keeping your breathing steady.','Stop the set when your hips sag or your lower back aches. Record time as reps in seconds.','Plank proper form tutorial'),
  ('cable-crunch','Cable Crunch','resistance','Cable machine with rope',array['Abs']::text[],'{}'::text[],'Kneel under the cable, hold the rope by your head, and curl your ribs toward your hips, then return slowly.','Move from your abs rather than pulling with your arms, and keep the weight moderate.','Cable Crunch proper form tutorial'),
  ('hanging-leg-raise','Hanging Leg Raise','resistance','Pull-up bar',array['Abs','Hip flexors']::text[],array['Forearms']::text[],'Hang with straight arms, raise your knees or legs toward your waist without swinging, then lower under control.','Start with bent knees and stop if you cannot control the swing.','Hanging Leg Raise proper form tutorial'),
  ('russian-twist','Russian Twist','resistance','Bodyweight or light weight',array['Obliques']::text[],array['Abs']::text[],'Sit leaning back slightly with your feet lifted or grounded, and rotate your torso side to side with control.','Keep your back long and skip the weight if you cannot rotate without rounding.','Russian Twist proper form tutorial'),
  ('treadmill','Treadmill','cardio','Treadmill',array['Cardiovascular system','Legs']::text[],'{}'::text[],'Choose a speed and incline you can sustain, keep an upright posture and a relaxed stride, and cool down gradually.','Do not hold the rails for balance at speed, and clip the safety key to your clothes.','Treadmill proper form tutorial'),
  ('stationary-bike','Stationary Bike','cardio','Stationary bike',array['Cardiovascular system','Quadriceps']::text[],array['Calves']::text[],'Adjust the seat so your knee is slightly bent at the bottom of the pedal stroke and pedal at a steady cadence.','Increase resistance gradually and keep your shoulders relaxed.','Stationary Bike proper form tutorial'),
  ('elliptical','Elliptical','cardio','Elliptical machine',array['Cardiovascular system','Legs']::text[],'{}'::text[],'Stand tall, keep your feet flat on the pedals, and use a smooth, steady stride.','Avoid leaning heavily on the handles.','Elliptical proper form tutorial'),
  ('rowing-machine','Rowing Machine','cardio','Rowing machine',array['Cardiovascular system','Back','Legs']::text[],array['Arms']::text[],'Drive with your legs first, then lean back slightly and pull the handle to your ribs. Reverse the order on the return.','Do not round your back and avoid yanking the handle at the start.','Rowing Machine proper form tutorial'),
  ('stair-climber','Stair Climber','cardio','Stair machine',array['Cardiovascular system','Glutes']::text[],array['Quadriceps']::text[],'Step with your whole foot, stand tall, and keep a steady pace without leaning on the rails.','Use the handles for light balance only and keep the pace controllable.','Stair Climber proper form tutorial'),
  ('walking','Walking','cardio','None',array['Cardiovascular system','Legs']::text[],'{}'::text[],'Walk at a brisk, comfortable pace with relaxed shoulders and natural arm swing.','Wear supportive shoes and build distance gradually.','Walking proper form tutorial'),
  ('running','Running','cardio','None or treadmill',array['Cardiovascular system','Legs']::text[],'{}'::text[],'Run at a pace where you can still breathe in a controlled way, landing under your body with a relaxed stride.','Warm up first and increase weekly distance gradually.','Running proper form tutorial')
on conflict (slug) do nothing;
insert into exercise_category_links (exercise_id, category_id)
select e.id, c.id from (values
  ('leg-press','lower-body'),
  ('leg-press','legs'),
  ('barbell-squat','lower-body'),
  ('barbell-squat','legs'),
  ('barbell-squat','free-weights'),
  ('goblet-squat','lower-body'),
  ('goblet-squat','legs'),
  ('goblet-squat','free-weights'),
  ('leg-extension','lower-body'),
  ('leg-extension','legs'),
  ('hamstring-curl','lower-body'),
  ('hamstring-curl','legs'),
  ('standing-calf-raise','lower-body'),
  ('standing-calf-raise','legs'),
  ('romanian-deadlift','lower-body'),
  ('romanian-deadlift','legs'),
  ('romanian-deadlift','pull'),
  ('romanian-deadlift','free-weights'),
  ('walking-lunge','lower-body'),
  ('walking-lunge','legs'),
  ('walking-lunge','free-weights'),
  ('hip-thrust','lower-body'),
  ('hip-thrust','legs'),
  ('chest-press-machine','upper-body'),
  ('chest-press-machine','push'),
  ('bench-press','upper-body'),
  ('bench-press','push'),
  ('bench-press','free-weights'),
  ('incline-dumbbell-press','upper-body'),
  ('incline-dumbbell-press','push'),
  ('incline-dumbbell-press','free-weights'),
  ('machine-shoulder-press','upper-body'),
  ('machine-shoulder-press','push'),
  ('dumbbell-shoulder-press','upper-body'),
  ('dumbbell-shoulder-press','push'),
  ('dumbbell-shoulder-press','free-weights'),
  ('lateral-raise','upper-body'),
  ('lateral-raise','push'),
  ('lateral-raise','free-weights'),
  ('triceps-pushdown','upper-body'),
  ('triceps-pushdown','push'),
  ('pec-deck-fly','upper-body'),
  ('pec-deck-fly','push'),
  ('lat-pulldown','upper-body'),
  ('lat-pulldown','pull'),
  ('seated-cable-row','upper-body'),
  ('seated-cable-row','pull'),
  ('pull-up','upper-body'),
  ('pull-up','pull'),
  ('bent-over-row','upper-body'),
  ('bent-over-row','pull'),
  ('bent-over-row','free-weights'),
  ('dumbbell-biceps-curl','upper-body'),
  ('dumbbell-biceps-curl','pull'),
  ('dumbbell-biceps-curl','free-weights'),
  ('hammer-curl','upper-body'),
  ('hammer-curl','pull'),
  ('hammer-curl','free-weights'),
  ('face-pull','upper-body'),
  ('face-pull','pull'),
  ('deadlift','lower-body'),
  ('deadlift','pull'),
  ('deadlift','free-weights'),
  ('plank','core'),
  ('cable-crunch','core'),
  ('hanging-leg-raise','core'),
  ('russian-twist','core'),
  ('treadmill','cardio'),
  ('stationary-bike','cardio'),
  ('elliptical','cardio'),
  ('rowing-machine','cardio'),
  ('stair-climber','cardio'),
  ('walking','cardio'),
  ('running','cardio')
) as v(es, cs) join exercises e on e.slug = v.es join exercise_categories c on c.slug = v.cs
on conflict do nothing;
insert into achievements (key, name, description, icon, rule, xp_reward, coin_reward) values
  ('first-workout','First Workout','Log your first completed workout.','dumbbell','{"type": "workouts", "threshold": 1}'::jsonb,25,10),
  ('seven-day-warrior','Seven-Day Warrior','Reach a 7-day workout streak.','flame','{"type": "workout_streak", "threshold": 7}'::jsonb,100,30),
  ('new-personal-record','New Personal Record','Beat your previous best on an exercise.','trophy','{"type": "prs", "threshold": 1}'::jsonb,50,20),
  ('consistency-king','Consistency King','Complete at least 80% of planned workouts across 4 weeks (and at least 8 sessions).','crown','{"type": "consistency_4w", "threshold": 80}'::jsonb,150,40),
  ('kitchen-honest','Kitchen Honest','Mark 7 days with a complete, honest food log.','utensils','{"type": "food_days", "threshold": 7}'::jsonb,100,30),
  ('trio-united','Trio United','Complete a team challenge together.','users','{"type": "team_challenge", "threshold": 1}'::jsonb,100,40),
  ('comeback-champion','Comeback Champion','Return to a workout after a break of 7 days or more.','rotate-ccw','{"type": "comeback", "threshold": 7}'::jsonb,75,25),
  ('level-5','Level 5','Reach level 5.','star','{"type": "level", "threshold": 5}'::jsonb,0,50)
on conflict (key) do nothing;
insert into cosmetic_items (key, kind, name, value, cost_coins) values
  ('title-rookie-plus','title','Title: Gym Regular','Gym Regular',50),
  ('title-iron','title','Title: Iron Mind','Iron Mind',120),
  ('title-legend','title','Title: Trio Legend','Trio Legend',300),
  ('frame-orange','frame','Frame: Sunrise Orange','#F28C28',60),
  ('frame-sky','frame','Frame: Sky Blue','#83D3F5',60),
  ('frame-green','frame','Frame: Fresh Green','#8DDE75',60),
  ('frame-navy','frame','Frame: Midnight Navy','#172B4D',150)
on conflict (key) do nothing;
